INSERT INTO SPOT_TYPE VALUES (1,"General","General","A");
INSERT INTO SPOT_TYPE VALUES (2,"Handicap","Handicap","B");
INSERT INTO SPOT_TYPE VALUES (3,"S Zone Commuter","S","C");
INSERT INTO SPOT_TYPE VALUES (4,"P Preferred Zone Commuter","P","D");
INSERT INTO SPOT_TYPE VALUES (5,"R Resident","R","E");
INSERT INTO SPOT_TYPE VALUES (6,"E Evening","E","F");
INSERT INTO SPOT_TYPE VALUES (7,"MX Motorcycle","MX","G");
INSERT INTO SPOT_TYPE VALUES (8,"MBA Permit","MBA","K");
INSERT INTO SPOT_TYPE VALUES (9,"C / CI General","C","M");
INSERT INTO SPOT_TYPE VALUES (10,"AR / ARI Reserved","AR","O");
INSERT INTO SPOT_TYPE VALUES (11,"Carpool","Carpool","P");
INSERT INTO SPOT_TYPE VALUES (12,"X / XI Executive","X","X");
INSERT INTO SPOT_TYPE VALUES (13,"GN Car / Motorcycle Combined Permit","GN","Q");

INSERT INTO LOT VALUES (1,"Lot 6A","6A",4);
INSERT INTO LOT VALUES (2,"Lot 14","14",1);

INSERT INTO LOT_SPOT_RELATIONSHIP VALUES (1,1,1,37);
INSERT INTO LOT_SPOT_RELATIONSHIP VALUES (2,1,2,3);
INSERT INTO LOT_SPOT_RELATIONSHIP VALUES (3,1,10,8);
INSERT INTO LOT_SPOT_RELATIONSHIP VALUES (4,2,1,50);
INSERT INTO LOT_SPOT_RELATIONSHIP VALUES (5,2,2,15);
INSERT INTO LOT_SPOT_RELATIONSHIP VALUES (6,2,5,20);